#app:
#  datasource:
#    jdbc-url: jdbc:postgresql://localhost:5432/demo2db
#    username: postgres
#    password: password
#    poll-size: 30
# postgres://rltdyjwprnwnah:c70bb8c0a5a88317295959d2b9239342a0b98e30656ea600271f8019af1e13a9@ec2-34-233-115-14.compute-1.amazonaws.com:5432/d46avir9fc39u1
# heroku postgres credentials
app:
  datasource:
    jdbc-url: jdbc:postgresql://ec2-34-233-115-14.compute-1.amazonaws.com:5432/d46avir9fc39u1
    username: rltdyjwprnwnah
    password: c70bb8c0a5a88317295959d2b9239342a0b98e30656ea600271f8019af1e13a9
    poll-size: 30

#springdoc:
#  swagger-ui:
#    path: /api/v1/

jwt:
  secret: asifisthiaq
  accessTokenExpirationDateInMs: 60000
  refreshTokenExpirationDateInMs: 300000
