#app:
#  datasource:
#    jdbc-url: jdbc:postgresql://localhost:5432/demo2db
#    username: postgres
#    password: password
#    poll-size: 30
# postgres://rltdyjwprnwnah:c70bb8c0a5a88317295959d2b9239342a0b98e30656ea600271f8019af1e13a9@ec2-34-233-115-14.compute-1.amazonaws.com:5432/d46avir9fc39u1
# heroku postgres credentials
#jdbc-url: jdbc:postgresql://ec2-34-233-115-14.compute-1.amazonaws.com:5432/d46avir9fc39u1
#username: rltdyjwprnwnah
#password: c70bb8c0a5a88317295959d2b9239342a0b98e30656ea600271f8019af1e13a9
#poll-size: 30
#elephant sql postgres credentials
app:
  datasource:
    jdbc-url: jdbc:postgres://rzumhkcr:I1-LaJHad14Mo8m4YIbQMoqUrOtrOOXS@tiny.db.elephantsql.com/rzumhkcr
    username: rzumhkcr
    password: I1-LaJHad14Mo8m4YIbQMoqUrOtrOOXS
    poll-size: 30

#springdoc:
#  swagger-ui:
#    path: /api/v1/
springdoc:
  swagger-ui:
    defaultModelsExpandDepth: -1

jwt:
  secret: asifisthiaq
  accessTokenExpirationDateInMs: 120000
  refreshTokenExpirationDateInMs: 300000


# Redis Config
  #  spring.redis.database=0
  #  spring.redis.host=localhost
  #  spring.redis.port=6379
  #  spring.redis.password=password
  #  spring.redis.timeout=60000
  #  time-to-live: 10S
#spring:
#  redis:
#    host: localhost
#    port: 6379
#    expire: 300 redis-17378.c301.ap-south-1-1.ec2.cloud.redislabs.com:17378

spring:
  redis:
    host: redis-17378.c301.ap-south-1-1.ec2.cloud.redislabs.com
    port: 17378
    expire: 300
    password: NNYFU174DnUd5MrCABm88x8tkXcaDORv