app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/demo2db
    username: postgres
    password: password
    poll-size: 30

springdoc:
  swagger-ui:
    path: /api/v1/

jwt:
  secret: asifisthiaq
  accessTokenExpirationDateInMs: 50000
  refreshTokenExpirationDateInMs: 9000000
